### ISSUE TITLE
fix: Virtual Service chart for Istio routing

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-api#54]
We need to modify the Virtual Service chart to reflect the routing we implemented to de-conflict the UI and API. Below is the example YAML from our running instance, and here is the current chart: https://github.com/defenseunicorns/leapfrogai-api/blob/main/chart/templates/vs.yaml

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: leapfrogai
  namespace: leapfrogai
spec:
  gateways:
  - istio-system/leapfrogai
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /leapfrogai-api/
    rewrite:
      uri: /
    route:
    - destination:
        host: api
        port:
          number: 8080
  - match:
    - uri:
        prefix: /openapi.json
    redirect:
      uri: /leapfrogai-api/openapi.json
```
